version: "3.8"
services:
  api:
    build: ./api/
    container_name: api
    ports:
      - "4000:4000"
    command: npm start
    environment:
      MONGO_URI: mongodb+srv://mejbrimed10:nnsTUg3qOKIoFehz@databaseecommerce.nlwhi.mongodb.net/?retryWrites=true&w=majority&appName=databaseecommerce
      JWT_SECRET: ecommerce
    volumes:
      - "./api/:/app"
      - "/app/node_modules"
    #image: mejbria9/api:latest  

  client:
    build: ./client/
    container_name: client
    ports:
      - "5173:5173"
    command: npm run dev
    environment:
      VITE_REACT_APP_API_URL: http://localhost:4000
      VITE_FLASK_APP_API_URL: http://localhost:5000
    volumes:
      - "./client/:/app"
      - "/app/node_modules"
    #image: mejbria9/client:latest  
  
  pythonnlp:
    build: ./python/
    container_name: pythonnlp
    ports:
      - "5000:5000"
    command: python NLP_Backend.py
    volumes:
      - "./python/:/app"
    #image: mejbria9/pythonnlp:latest
