replicaCount: 3

image:
  repository: mejbri1998/pythonnlp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: false

serviceAccount:
  create: true
  name: ecommerce-nlp-pythonnlp

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
