apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: mejbri1998/client:latest
        ports:
        - containerPort : 5173
        envFrom:
        - configMapRef:
            name: app-configmap